version: '3'

services:

  mongo:
    container_name: conductor-mongo
    image: mongo:6.0.8
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - ./volumes/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Password1234

  mongo-express:
    container_name: conductor-mongo-express
    image: mongo-express:latest
    restart: always
    ports:
      - "27018:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Password1234
      ME_CONFIG_MONGODB_URL: mongodb://root:Password1234@mongo:27017/
    depends_on:
      - mongo

  redis:
    container_name: conductor-redis
    image: redis:6.2.13-alpine
    ports:
      - "6379:6379"
#    volumes:
#      - ./volumes/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

#  elasticsearch:
#    image: elasticsearch:7.17.10
#    container_name: conductor-elasticsearch
#    environment:
#      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
#      - transport.host=0.0.0.0
#      - discovery.type=single-node
#      - xpack.security.enabled=false
#    volumes:
#      - ./volumes/elasticsearch:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    healthcheck:
#      test: wget http://localhost:9200/ -O /dev/null
#      interval: 5s
#      timeout: 5s
#      retries: 12
#    logging:
#      driver: "json-file"
#      options:
#        max-size: "1k"
#        max-file: "3"