
spring:
  application:
    name: nx-conductor
  data:
    mongodb:
      uri: mongodb://root:Password1234@localhost:27017
      database: conductor

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true

server:
  http2:
    enabled: true

conductor:
  indexing:
    enabled: false
  server:
    cors: unsecure

#  elasticsearch:
#    url: https://test-nx-conductor.ent.eu-west-1.aws.found.io
##    cluster-health-color: yellow
#    username: private-key
#    password: private-12cecgwzwmq5g6harj1bqqfi

#  lock:
#    server-type: SINGLE
logging:
  level:
    root: info
